### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Sexy-Frog** [p0358/wireshark_titanfallproto#1]
I want to run it successfully in apex Legends but it doesn't work.
Please contact me on Discord if you want to help.
I'm happy#8232

**Comment by p0358** [comment]
Check out the updated Windows instructions, now they should be easier to follow/reproduce. And for encryption key you may need to set up a MITM kind of proxy to grab the encryption key once you first connect to a server or use some other method (in Titanfalls you could simply read it from memory, but in Apex there's the concern of anticheat that's a separate matter...).
